"""create orders table

Revision ID: 62c0def6ffe0
Revises: 4b06348c6f42
Create Date: 2024-09-23 19:12:54.107139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c0def6ffe0'
down_revision: Union[str, None] = '4b06348c6f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('walker_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'walker_name')
    # ### end Alembic commands ###
